# **Why use NumPy**
Python lists are flexible but slow for numerical computing because they:

- Store elements as pointers instead of a continuous block of memory.
- Lack vectorized operations, relying on loops instead.
- Have significant overhead due to dynamic typing.

**NumPy's Superpowers:**
- Faster than Python lists (C-optimized backend)
- Uses less memory (efficient storage)
- Supports vectorized operations (no explicit loops needed)
- Has built-in mathematical functions

## NumPy vs. Python Lists – Performance Test
Example 1: Adding Two Lists vs. NumPy Arrays

In [ ]:
import numpy as np
import time

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", end - start)

**Key Takeaway:** NumPy is significantly faster because it performs operations in C, avoiding Python loops.



## Creating NumPy Arrays

In [4]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


## Memory Efficiency – NumPy vs. Lists
NumPy arrays use significantly less memory compared to Python lists

In [5]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


## Vectorization – No More Loops!
NumPy avoids loops by applying operations to entire arrays at once using SIMD (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a CPU-level optimization provided by modern processors.

Example 2: Squaring Elements

**NumPy is cleaner and faster!**

In [9]:
# Python list (loop-based)
list_squares = [x ** 2 for x in list1]

# NumPy (vectorized)
numpy_squares = arr1 ** 2

- Comparing squaring elements using normal Python loop (not list comprehension) vs NumPy vectorized squaring.

In [10]:
import numpy as np
import time

# Create big list
list1 = list(range(1000000))   # 10 lakh values

# Python loop-based squaring
start = time.time()
list_squares = []
for x in list1:
    list_squares.append(x ** 2)
end = time.time()
print("Python loop time:", end - start)

# NumPy vectorized squaring
arr1 = np.array(list1)  # convert only once
start = time.time()
numpy_squares = arr1 ** 2
end = time.time()
print("NumPy array time:", end - start)


Python loop time: 0.45592737197875977
NumPy array time: 0.005709648132324219


## **Summary**
- NumPy is faster than Python lists because it is optimized in C.
- It consumes less memory due to efficient storage.
- It provides vectorized operations, removing the need for slow loops.
- Essential for data science and machine learning workflows.


## **Exercises for Practice**

Q. Create a NumPy array with values from 10 to 100 and print its shape.

In [14]:
import numpy as np
arr1 = np.arange(10,101)
print(arr1)
print("The shape of the array is",arr1.shape)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
The shape of the array is (91,)


Q. Compare the time taken to multiply two Python lists vs. two NumPy arrays.

In [23]:
import numpy as np
import time

# Create two large lists
list1 = list(range(1000000))
list2 = list(range(1000000, 2000000))

start = time.time()
result_list = []
for a, b in zip(list1, list2):
    result_list.append(a * b)
end = time.time()
print("Python list multiplication time:", end - start)

# NumPy 
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result_numpy = arr1 * arr2
end = time.time()
print("NumPy array multiplication time:", end - start)


Python list multiplication time: 0.21621465682983398
NumPy array multiplication time: 0.004259347915649414


Q. Find the memory size of a NumPy array with 1 million elements.

In [27]:
import numpy as np

arr = np.arange(1_000_000)   #np.arange(1_000_000) creates 1,000,000 integers (default int64 on most 64-bit systems)
print("Memory size in bytes:", arr.nbytes)


Memory size in bytes: 8000000
