# **Indexing and slicing**

## Indexing (Same as Python Lists)

In [1]:
import numpy as np
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


## Slicing (Extracting Parts of an Array)

In [2]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


**Slicing returns a view, not a copy! Changes affect the original array.**

This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

**Why does this happen?**

Memory Efficiency: Avoids unnecessary copies, making operations faster and saving memory.
Performance: Enables faster access and manipulation of large datasets without duplicating data.

In [3]:
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[ 10 999  30  40  50]


Use .copy() if you need an independent copy.

In [4]:
sliced = arr[1:4].copy()   # creates a separate copy
sliced[0] = 999            # modify copy
print(arr)                 # original remains same
print(sliced)              # modified copy

[ 10 999  30  40  50]
[999  30  40]


## Fancy Indexing & Boolean Masking
This is a powerful way to filter large datasets efficiently!

- Fancy Indexing (Select Multiple Elements)

In [5]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


- Boolean Masking (Filter Data)

In [6]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


## Summary
- NumPy arrays are faster, memory-efficient alternatives to lists.
- You can create arrays using np.array(), np.zeros(), np.ones(), etc.
- Indexing & slicing allow efficient data manipulation.
- Reshaping & flattening change array structures without copying data.
- Fancy indexing & boolean masking help filter and access specific data.

## **Exercises for Practice**

Q1.Create a 3×3 array filled with random numbers and print its shape.

In [12]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print("Shape =",arr1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape = (3, 3)


Q2.Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [17]:
arr = np.array([1.1, 2.2, 3.3])   # float array
int_arr = arr.astype(int)         # convert to integers
print(int_arr)
print("Type =", int_arr.dtype)

[1 2 3]
Type = int64


Q3.Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6])
even = arr%2 == 0
print(arr[even])

[2 4 6]


Q4. Reshape a 1D array of size 9 into a 3×3 matrix.

In [34]:
arr = np.array([1,2,3,4,5,6,7,8,9])
reshape = arr.reshape(3,3)
print(reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Q5. Use boolean masking to filter numbers greater than 50 in an array.

In [36]:
arr = np.array([23,51,46,90,100,80,23,32,60])
greater = arr>50
print(arr[greater])

[ 51  90 100  80  60]


Q6.Create a 5×5 array of zeros.

In [39]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Q7. Create a 1D NumPy array containing values from 1 to 20.

In [42]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Q8. Generate a 3x4 array of random integers between 10 and 50, and print its shape.

arr = np.array([[12,15,23,90],[21,56,43,87],[65,98,76,3]])
print(arr)
shape = arr.shape
print(shape)

Q9. Convert an array of floats to integers using astype().

In [50]:
arr = np.array([23,45,90,65])
int_array = arr.astype(int)
print(arr)
print("Type :",int_array.dtype)

[23 45 90 65]
Type : int64


Q10. From the array np.array([10,20,30,40,50,60]), extract the elements 20, 30, 40 using slicing.

In [52]:
arr = np.array([10,20,30,40,50,60])
n = arr[1:4]
print(n)

[20 30 40]


Q11. From the array [2, 7, 12, 15, 20, 25], extract the values divisible by 5.

In [59]:
arr1 = np.array([2, 7, 12, 15, 20, 25])
div = arr1%5 == 0
print(arr1[div])

[15 20 25]


Q12. Given arr = np.array([2,4,6]), multiply every element by 3 without using loops.

In [61]:
import numpy as np

arr = np.array([2, 4, 6])
result = arr * 3
print(result)


[ 6 12 18]


Q13. Find the sum, mean, min, and max of the array np.array([12, 45, 8, 32, 19]).

In [62]:
import numpy as np

arr = np.array([12, 45, 8, 32, 19])

print("Sum =", arr.sum())
print("Mean =", arr.mean())
print("Minimum =", arr.min())
print("Maximum =", arr.max())


Sum = 116
Mean = 23.2
Minimum = 8
Maximum = 45


Q14. Sort the array np.array([21,5,17,9,50]) in ascending order.

In [63]:
import numpy as np

arr = np.array([21, 5, 17, 9, 50])
sorted_arr = np.sort(arr)

print(sorted_arr)


[ 5  9 17 21 50]


Q15. Reshape a 1D array of size 16 into a 4×4 matrix.

In [64]:
import numpy as np

arr = np.arange(1, 17)      # 1D array with 16 elements
matrix = arr.reshape(4, 4)  # reshape into 4×4 matrix

print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
