In [32]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])

1. np.mean() – Compute the mean (average) of an array.

In [10]:
a = np.mean(arr)
print(a)

3.0


2. np.std() – Compute the standard deviation of an array.

In [9]:
a = np.std(arr)
print(a)

1.4142135623730951


3. np.var() – Compute the variance of an array.

In [8]:
a = np.var(arr)
print(a)

2.0


4. np.min() – Compute the minimum value of an array.

In [11]:
a = np.min(arr)
print(a)

1


5. np.max() – Compute the maximum value of an array.

In [12]:
a = np.max(arr)
print(a)

5


6. np.sum() – Compute the sum of all elements in an array.

In [14]:
a = np.sum(arr)
print(a)

15


7. np.prod() – Compute the product of all elements in an array.

In [15]:
a = np.prod(arr)
print(a)

120


8. np.percentile() – Compute the percentile of an array.

In [17]:
a = np.percentile(arr,50)
print(a)

3.0


9. np.median() – Compute the median of an array.

In [19]:
a = np.median(arr)
print(a)

3.0


10. np.argmin() – Return the index of the minimum value in an array.

In [20]:
a = np.argmin(arr)
print(a)

0


11. np.argmax() – Return the index of the maximum value in an array.

In [21]:
a = np.argmax(arr)
print(a)

4


12. np.corrcoef() – Compute the correlation coefficient matrix of two arrays.

In [22]:
a = np.corrcoef(arr)
print(a)

1.0


13. np.unique() – Find the unique elements of an array.

In [24]:
arr2 = np.array([22,244,87,22,1,2,3,2,1,98,55])
a = np.unique(arr2)
print(arr2)

[ 22 244  87  22   1   2   3   2   1  98  55]


14. np.diff() – Compute the n-th differences of an array.

In [25]:
a = np.diff(arr)
print(a)

[1 1 1 1]


15. np.cumsum() – Compute the cumulative sum of an array.

In [26]:
a = np.cumsum(arr)
print(a)

[ 1  3  6 10 15]


16. np.linspace() – Create an array with evenly spaced numbers over a specified interval.

In [31]:
a = np.linspace(0, 10, 5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


17. np.log() – Compute the natural logarithm of an array.

In [33]:
a = np.log(arr)
print(a)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


18. np.exp() – Compute the exponential of an array.

In [34]:
a = np.exp(arr)
print(a)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
