Q1.Create a NumPy array of first 50 even numbers.

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(2, 2*51 ,2)
print(arr1)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Q2. Generate a 5×5 matrix with random integers between 1 and 100.

In [5]:
arr1 = np.random.randint(1,101,(5,5))
print(arr1)

[[53 62 36 19 13]
 [48 98 77 32 89]
 [95 33 26 92 57]
 [53 90 13 35 34]
 [23 70 50 25 34]]


Q3. Create an array from 20 to 2 with step −2.

In [6]:
arr1 = np.arange(20,1,-2)
print(arr1)

[20 18 16 14 12 10  8  6  4  2]


Q4. Convert a 1D array into a 5×5 2D array.

In [13]:
arr1 = np.random.randint(1,50,(1,25))
print(arr1)
reshaped = arr1.reshape((5,5))
print(reshaped)

[[ 7 47 41 25 39 20  4  7 10  8  5 49 34 41 35 33  5 30 48 46 44 20 24 46
  16]]
[[ 7 47 41 25 39]
 [20  4  7 10  8]
 [ 5 49 34 41 35]
 [33  5 30 48 46]
 [44 20 24 46 16]]


Q5. Replace negative values in an array with 0.

In [19]:
arr1 = np.random.randint(-50,50,(3,3))
print(arr1)
arr1[arr1<0] = 0
print(arr1)    

[[ -1  49  13]
 [ 38  41   0]
 [ 48 -25  28]]
[[ 0 49 13]
 [38 41  0]
 [48  0 28]]


Q6.Given an array [10, 20, 30, 40, 50], calculate cumulative sum and cumulative product.

In [7]:
import numpy as np
arr1 = np.array([10,20,30,40])
print(arr1)
print("cumulative sum ")
csum = np.cumsum(arr1)
print(csum)
print("cumulative Product ")
cprod = np.cumprod(arr1)
print(cprod)

[10 20 30 40]
cumulative sum 
[ 10  30  60 100]
cumulative Product 
[    10    200   6000 240000]


Q7. Find unique values and their counts in an array.

In [8]:
import numpy as np
arr = np.array([10, 20, 10, 30, 20, 40, 10, 30])
unique_vals, counts = np.unique(arr, return_counts=True)
print("Unique values:", unique_vals)
print("Counts:", counts)

Unique values: [10 20 30 40]
Counts: [3 2 2 1]


Q8. Multiply two matrices without using loops.

In [4]:
import numpy as np
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
result = matrix1 @ matrix2
print(result)

[[19 22]
 [43 50]]


Q9.Given two arrays, return only the common elements.

In [8]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,6,7,8,9])
a = np.intersect1d(arr1,arr2)
print(a)

[1]


In [9]:
#Union
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,6,7,8,9])
a = np.union1d(arr1,arr2)
print(a)

[1 2 3 4 5 6 7 8 9]


Q10.Create a 3D NumPy array and extract:
- first row from each matrix
- last column from each matrix

In [15]:
arr = np.array([
    [ [1, 2, 3], [4, 5, 6] ],      
    [ [7, 8, 9], [10, 11, 12] ]    
])
print(arr)
first_rows = arr[:, 0, :]
print("\nFirst row from each matrix:\n", first_rows)
last_columns = arr[:, :, -1]
print("\nLast column from each matrix:\n", last_columns)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

First row from each matrix:
 [[1 2 3]
 [7 8 9]]

Last column from each matrix:
 [[ 3  6]
 [ 9 12]]


Q11.Implement matrix multiplication manually using broadcasting

In [21]:
import numpy as np
arr1 = np.random.randint(1, 10, (3, 3))   # A (3×3)
arr2 = np.random.randint(1, 10, (3, 3))   # B (3×3)
# Manual matrix multiplication using broadcasting
result = (arr1[:, :, None] * arr2.T[None, :, :]).sum(axis=1)
print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)
print("\nMatrix Multiplication (Broadcasting):\n", result)


Array 1:
 [[8 1 3]
 [3 8 2]
 [8 3 5]]

Array 2:
 [[6 8 1]
 [5 6 5]
 [9 3 2]]

Matrix Multiplication (Broadcasting):
 [[59 61 81]
 [84 73 55]
 [77 83 91]]


Q12. Sort 2D array by the 2nd column.

In [22]:
import numpy as np
arr = np.array([
    [10, 3,  50],
    [40, 1,  20],
    [30, 2,  90]
])
sorted_arr = arr[np.argsort(arr[:, 1])]
print(sorted_arr)


[[40  1 20]
 [30  2 90]
 [10  3 50]]
